# Generated by Django 4.2.11 on 2024-05-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SituationAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100)),
                ('suggestion', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='APILog',
        ),
    ]
